### ISSUE TITLE
Jailbreak Detected on M1 Macs

### ISSUE THREAD

**Issue by miguelsolans** [thii/DTTJailbreakDetection#12]
With the new M1 architecture, users are able to run both iOS Apps on the Mac. However, DTTJailbreakDetection is blocking due to jailbreak detection

**Comment by thii** [comment]
Do you mind submitting a fix?

**Comment by miguelsolans** [comment]
> Do you mind submitting a fix?

I could try. Maybe next week.

**Comment by skuske** [comment]
Add this

```
    if (@available(iOS 14.0, *)) {
        if ([NSProcessInfo processInfo].isiOSAppOnMac)
        {
            return NO;
        }
    }
```

right after 

`#if !(TARGET_IPHONE_SIMULATOR)`

in `DTTJailbreakDetection.m`

That will at least bypass the jailbreak check on M1 devices by always returning `NO`

**Comment by oscarshaitan** [comment]
any updates on this?

**Comment by brendansiow** [comment]
any update? coming from flutter as well 😬

**Comment by hcminh** [comment]
have same issue, hope fix soon 😌
