### ISSUE TITLE
Where do I implement the function?

### ISSUE THREAD

**Issue by jweinraub** [thii/DTTJailbreakDetection#5]
Do I put the alert into a viewDidAppear block?

```
-(void)viewDidAppear:(BOOL)animated
{
     if ([DTTJailbreakDetection isJailbroken]) 
    {
         // code
    }
}
```

If I do that, the main view still loads.  Can I keep it at the LaunchScreenStoryBoard, so it doesn't even show the app, if i wanted?  

Pardon my ignorance on this subject I am learning and seeing how this works.

Thanks

**Comment by thii** [comment]
If you want to your app to crash if it runs on a jailbroken device:

```objc
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
     if ([DTTJailbreakDetection isJailbroken]) {
         exit(1);
    }
    return YES;
}
 ```
